name: Actualizar eventos
on:
  schedule:
    - cron: '0 12 * * *'  # Ejecuta diariamente a las 12:00 PM UTC
  workflow_dispatch:       # Permite ejecución manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar dependencias
        run: pip install beautifulsoup4 requests
      
      - name: Ejecutar scraper
        run: python scraper.py
      
      - name: Subir cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add eventos.json
          git commit -m "Actualización automática: $(date +'%d-%m-%Y %H:%M')"
          git push
