name: Actualizar eventos
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: pip install beautifulsoup4 requests
      
      - name: Run scraper
        run: python scraper.py
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add eventos.json
          git commit -m "Actualización automática: $(date +'%Y-%m-%d %H:%M')"
          git push
